#!/bin/sh
while getopts "z:" arg; do
  case $arg in
    z)
      zapp=$OPTARG
      ;;
  esac
done
cd temp-zapps/$zapp
npm install
chmod +x ./bin/setup && chmod +x ./bin/startup
./bin/setup && ./bin/startup
sleep 20







