version: '3.5'

services:
  sprinkles:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zokrates
      - timber
      - ganache
    volumes:
      - ./src/:/app/src:delegated
      - ./build:/app/build
      - ./examples/:/app/examples/:delegated
      - ./circuits/:/app/circuits:delegated
      - ./test/:/app/test:delegated
      - ./config/:/app/config:delegated
    environment:
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      LOG_LEVEL: debug
    networks:
      - sprinkles_network

  zokrates:
    image: docker.pkg.github.com/eyblockchain/zokrates-worker/zokrates_worker:1.0.4
    #command: npm run zok
    volumes:
      - ./circuits/:/app/circuits:delegated
      - ./proving-files/:/app/output:delegated
      - ./examples/:/app/examples/:delegated
      - ./src/utils/write-vk.mjs:/app/write-vk.mjs
    environment:
      PROVING_SCHEME: 'gm17'
    ports:
      - '8080:80'
    networks:
      - sprinkles_network

  timber:
    image: eyblockchain/timber:v3.0.3
    restart: on-failure
    depends_on:
      - timber-mongo
      - ganache
    volumes:
      - ./config/:/app/config
      - ./contracts/:/app/contracts:consistent
      - ./build/:/app/build:consistent
    ports:
      - '9000:80'
    environment:
      HASH_TYPE: 'mimc'
      LOG_LEVEL: 'silly'
      UNIQUE_LEAVES: 'true'
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      CONTRACT_LOCATION: 'default'
      MONGO_HOST: mongodb://timber-mongo
      MONGO_PORT: 27017
      MONGO_NAME: merkle_tree
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    networks:
      - sprinkles_network

  #The database storing the merkle tree
  timber-mongo:
    image: docker.pkg.github.com/eyblockchain/timber-mongo/timber_mongo:73c12fc8bd35d4cab739c836b738b416f6db64ba
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=merkle_tree
    volumes:
      - timber-mongo-volume:/data/db
    networks:
      - sprinkles_network

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli --accounts=10 --defaultBalanceEther=1000 --gasLimit=100000000 --deterministic
    ports:
      - '8545:8545'
    networks:
      - sprinkles_network

  truffle:
    image: docker.io/westlad/contract_deployer:v1.0
    volumes:
      - ./contracts/:/truffle/contracts/:ro
      - ./migrations/:/truffle/migrations/:ro
      - ./truffle-config.js:/truffle/truffle-config.js:ro
      - ./build/:/truffle/build/:cached
      - ./examples/:/app/examples/:delegated
    networks:
      - sprinkles_network
    depends_on:
      - ganache
    command: ["truffle", "migrate", "--reset", "--network", "development_ganache"]

volumes:
  timber-mongo-volume: {}

networks:
  sprinkles_network:
    name: sprinkles_network
