services:
  zapp:
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zapp-mongo
    volumes:
      - ./build:/app/build
      - ./orchestration/:/app/orchestration:delegated
      - ./test/:/app/test:delegated
    environment:
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      RPC_URL: ws://ganache:8545
      DEFAULT_ACCOUNT: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
      LOG_LEVEL: info
      MONGO_HOST: mongodb://zapp-mongo
      MONGO_PORT: 27019
      MONGO_NAME: zapp_db
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    networks:
      - zapp_network

  zapp2:
    ports:
      - '3001:3000'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zapp-mongo
    volumes:
      - ./build:/app/build
      - ./orchestration/:/app/orchestration:delegated
      - ./test/:/app/test:delegated
    environment:
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      RPC_URL: ws://ganache:8545
      DEFAULT_ACCOUNT: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8'
      KEY: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'
      LOG_LEVEL: info
      MONGO_HOST: mongodb://zapp-mongo
      MONGO_PORT: 27019
      MONGO_NAME: zapp_db
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    networks:
      - zapp_network    

  zokrates:
    image: ghcr.io/jtcoolen/zokrates-worker-api:latest
    # the following image is for arm64 architecture. Uncomment the following lines and comment the above line if you are using ARM
    # image: ghcr.io/eyblockchain/zokrates-worker-starlight:v0.2
    # platform: linux/arm64/v8
    volumes:
      - ./circuits/:/app/circuits:delegated
      - ./proving-files/:/app/output:delegated
    environment:
      PROVING_SCHEME: 'g16'
    ports:
      - '8080:80'
    networks:
      - zapp_network

  zokrates2:
    image: ghcr.io/jtcoolen/zokrates-worker-api:latest
    # the following image is for arm64 architecture. Uncomment the following lines and comment the above line if you are using ARM
    # image: ghcr.io/eyblockchain/zokrates-worker-starlight:v0.2
    # platform: linux/arm64/v8
    volumes:
      - ./circuits/:/app/circuits:delegated
      - ./proving-files/:/app/output:delegated
    environment:
      PROVING_SCHEME: 'g16'
    ports:
      - '8081:80'
    networks:
      - zapp_network    

  timber:
    build: 
      context: https://github.com/EYBlockchain/timber.git#starlight/zscaler:merkle-tree
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - timber-mongo
    volumes:
      - ./config/:/app/config
      - ./build/:/app/build:consistent
    ports:
      - '9000:80'
    environment:
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt
      HASH_TYPE: 'mimc'
      LOG_LEVEL: 'silly'
      UNIQUE_LEAVES: 'true'
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      RPC_URL: ws://ganache:8545
      DEFAULT_ACCOUNT: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
      CONTRACT_LOCATION: 'default'
      MONGO_HOST: mongodb://timber-mongo
      MONGO_PORT: 27017
      MONGO_NAME: merkle_tree
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    networks:
      - zapp_network

  timber2:
    build: 
      context: https://github.com/EYBlockchain/timber.git#starlight/zscaler:merkle-tree
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - timber-mongo
    volumes:
      - ./config/:/app/config
      - ./build/:/app/build:consistent
    ports:
      - '9001:80'
    environment:
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt
      HASH_TYPE: 'mimc'
      LOG_LEVEL: 'silly'
      UNIQUE_LEAVES: 'true'
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      RPC_URL: ws://ganache:8545
      DEFAULT_ACCOUNT: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8'
      KEY: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'
      CONTRACT_LOCATION: 'default'
      MONGO_HOST: mongodb://timber-mongo
      MONGO_PORT: 27017
      MONGO_NAME: merkle_tree
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    networks:
      - zapp_network    

  #The database storing the merkle tree
  timber-mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=merkle_tree
    ports:
      - "2022:27017"  
    volumes:
      - timber-mongo-volume:/data/db
      - ./config:/app/config/
    networks:
      - zapp_network

  timber-mongo2:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=merkle_tree
    ports:
      - "2023:27017"   
    volumes:
      - timber-mongo-volume2:/data/db
    networks:
      - zapp_network  

    #The database storing commitments
  zapp-mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "2020:27017"    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=zapp_db
    volumes:
      - zapp-commitment-volume:/data/db
    networks:
      - zapp_network

  zapp-mongo2:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "2021:27017"  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=zapp_db
    volumes:
      - zapp-commitment-volume2:/data/db
    networks:
      - zapp_network    

  
  ganache:
    image: ethereumoptimism/hardhat-node
    ports:
      - "8545:8545"
    networks:
      - zapp_network

  hardhat-node:
    image: trufflesuite/ganache:v7.4.4
    command: --accounts=10  --miner.defaultTransactionGasLimit=200000000000 --gasLimit=2000000000000 --chain.allowUnlimitedContractSize --gasPrice=1 --deterministic -i 1337
    ports:
      - "8545:8545"
    networks:
      - zapp_network

  deployer:
    build:
      context: .
      dockerfile: Dockerfile.deployer
    volumes:
      - ./build:/app/build
      - ./contracts/:/app/contracts/
      - ./orchestration/:/app/orchestration:delegated
    environment:
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt
      RPC_URL: http://ganache:8545
      DEFAULT_ACCOUNT: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
    networks:
      - zapp_network

volumes:
  timber-mongo-volume: {}
  timber-mongo-volume2: {}
  zapp-commitment-volume: {}
  zapp-commitment-volume2: {}

networks:
  zapp_network:
    name: zapp_network
